# Fase 1 - Comprensión y Preparación del Dataset

## Dataset Energy Efficiency

Curso: Introducción a la Inteligencia Artificial

## 1. Objetivo

Analizar las características arquitectónicas de edificios residenciales y su relación con las cargas de calefacción y refrigeración, con el fin de preparar el dataset para etapas posteriores de clustering y clasificación.

#### Importación de librerías

In [6]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler

## Descripción del problema

El objetivo de este proyecto consiste en analizar la relación entre las características arquitectónicas de edificios residenciales y su comportamiento energético.

A partir de variables como compacidad relativa, área de superficie, altura, orientación y área de acristalamiento, se busca identificar patrones que permitan estimar la carga de calefacción (Y1) y la carga de refrigeración (Y2).

Posteriormente, estos datos serán utilizados para las fases 2 y 3.

## 2. Selección y descripción del dataset

El dataset fue obtenido del repositorio UCI Machine Learning Repository y almacenado en formato Excel (.xlsx). Posteriormente se cargó en Python utilizando Pandas para realizar el proceso de análisis y preparación.

El dataset contiene 768 registros con ocho variables de entrada (X1-X8) que describen características arquitectónicas de los edificios y dos variables de salida (Y1 y Y2), correspondientes a la carga de calefacción y carga de refrigeración. Todas las variables son numericas.

### Variables entrada

- X1: Compacidad relativa
- X2: Área de superficie
- X3: Área de pared
- X4: Área de techo
- X5: Altura total
- X6: Orientación
- X7: Área de acristalamiento
- X8: Distribución del acristalamiento

### Variables salida

- Y1: Carga de calefacción
- Y2: Carga de refrigeración


### Selección de datos

Se dejan las variables del X1-X8 ya que son características de entrada para el modelado, mientras que Y1 y Y2 se conservaron como variables salida debido a que representan los valores que se desean predecir.

In [34]:
df = pd.read_excel("../data/raw/ENB2012_data.xlsx")

df.head()

     X1     X2     X3      X4   X5  X6   X7  X8     Y1     Y2
0  0.98  514.5  294.0  110.25  7.0   2  0.0   0  15.55  21.33
1  0.98  514.5  294.0  110.25  7.0   3  0.0   0  15.55  21.33
2  0.98  514.5  294.0  110.25  7.0   4  0.0   0  15.55  21.33
3  0.98  514.5  294.0  110.25  7.0   5  0.0   0  15.55  21.33
4  0.90  563.5  318.5  122.50  7.0   2  0.0   0  20.84  28.28

### Analisis Exploratorio

Con 768 registros y 10 columnas realizamos una estadistica descriptiva y teniendo en cuenta las variables de entrada verificamos como la influencia de la orientación, altura, area de acristalamiento se correlacionan para las variables de salida

In [36]:
df.head()
df.shape

(768, 10)

In [37]:
df.describe()

,X1,X2,X3,X4,X5,X6,X7,X8,Y1,Y2
count,768.000000,768.000000,768.000000,768.000000,768.00000,768.000000,768.000000,768.00000,768.000000,768.000000
mean,0.764167,671.708333,318.500000,176.604167,5.25000,3.500000,0.234375,2.81250,22.307195,24.587760
std,0.105777,88.086116,43.626481,45.165950,1.75114,1.118763,0.133221,1.55096,10.090204,9.513306
min,0.620000,514.500000,245.000000,110.250000,3.50000,2.000000,0.000000,0.00000,6.010000,10.900000
25%,0.682500,606.375000,294.000000,140.875000,3.50000,2.750000,0.100000,1.75000,12.992500,15.620000
50%,0.750000,673.750000,318.500000,183.750000,5.25000,3.500000,0.250000,3.00000,18.950000,22.080000
75%,0.830000,741.125000,343.000000,220.500000,7.00000,4.250000,0.400000,4.00000,31.667500,33.132500
max,0.980000,808.500000,416.500000,220.500000,7.00000,5.000000,0.400000,5.00000,43.100000,48.030000

In [38]:
df.groupby("X6")[["Y1","Y2"]].mean()

           Y1         Y2
X6
2   22.312865  24.604531
3   22.380677  24.312552
4   22.259875  24.480313
5   22.275365  24.953646

In [39]:
df.groupby("X5")[["Y1","Y2"]].mean()

            Y1         Y2
X5
3.5  13.338505  16.071432
7.0  31.275885  33.104089

In [40]:
df.groupby("X7")[["Y1","Y2"]].mean()

             Y1         Y2
X7
0.00  14.286375  19.706250
0.10  20.357167  22.935542
0.25  22.756917  24.892625
0.40  25.411667  26.911417

In [41]:
corr = df.corr(numeric_only=True)

corr[["Y1","Y2"]].sort_values("Y1", ascending=False)

          Y1        Y2
Y1  1.000000  0.975862
Y2  0.975862  1.000000
X5  0.889430  0.895785
X1  0.622272  0.634339
X3  0.455671  0.427117
X7  0.269842  0.207505
X8  0.087368  0.050525
X6 -0.002587  0.014290
X2 -0.658120 -0.672999
X4 -0.861828 -0.862547

La orientación presenta una influencia muy baja sobre las cargas de calefacción y refrigeración.
La altura total presenta una fuerte influencia sobre las cargas energéticas. Los edificios con una altura de 7 metros requieren aproximadamente el doble de carga de calefacción y refrigeración respecto a los edificios de 3.5 metros.
A medida que aumenta el área de acristalamiento también aumentan las cargas de calefacción y refrigeración. Esto sugiere que la cantidad de superficie acristalada tiene un impacto directo en el comportamiento energético del edificio.


El análisis de correlación muestra que la altura total (X5) es la variable con mayor relación positiva respecto a las cargas energéticas.
La compacidad relativa (X1) también presenta una correlación positiva moderada.
Por otro lado, el área de techo (X4) y el área superficial (X2) presentan correlaciones negativas fuertes, indicando que al aumentar estas variables las cargas energéticas tienden a disminuir.
La orientación (X6) prácticamente no presenta relación con las variables de salida.

## 3. Identificación de Problemas de Calidad (Limpieza)

### 3.1. Valores Faltantes

In [14]:
df.isnull().sum()

X1    0
X2    0
X3    0
X4    0
X5    0
X6    0
X7    0
X8    0
Y1    0
Y2    0
dtype: int64

### 3.2. Valores Duplicados

In [15]:
df.duplicated().sum()

np.int64(0)

### 3.3. Datos atipicos

Se realizó una revisión estadística mediante la función describe() para identificar posibles valores extremos en las variables del dataset.

No se observaron valores fuera de los rangos esperados según la descripción del problema y la documentación del conjunto de datos.

### 3.4. Variables irrelevantes o inconsistentes


En la selección y analisis exploratorio del dataset, no se evidencia que ninguna variable fuera irrelevante ya que todas sirven para la resolución del problema, adicional se verifico la consistencia de las mismas verificando la correlación de algunas variables de entrada respectoa a las de salida

## 4. Limpieza e imputación

Se verificó la calidad del conjunto de datos mediante la revisión de valores faltantes, registros duplicados, inconsistencias y posibles valores atípicos.

Los resultados obtenidos indican que:

- No existen valores faltantes.
- No se encontraron registros duplicados.
- No se identificaron inconsistencias en los tipos de datos.
- No se detectaron valores atípicos relevantes para el problema.

Por lo tanto, no fue necesario eliminar registros ni realizar correcciones sobre el dataset original.

### 4.1 Simulación de valores faltantes

El dataset original no presenta valores faltantes. Sin embargo, se simularon algunos valores nulos en las variables X1, X3 y X7.

Posteriormente se aplicó imputación por media, reemplazando cada valor faltante por el promedio de la respectiva variable.

In [23]:
df_imp = df.copy()

df_imp.loc[10, "X1"] = np.nan
df_imp.loc[50, "X3"] = np.nan
df_imp.loc[100, "X7"] = np.nan

In [24]:
df_imp.isnull().sum()

X1    1
X2    0
X3    1
X4    0
X5    0
X6    0
X7    1
X8    0
Y1    0
Y2    0
dtype: int64

### 4.2 Imputación

La imputación se realizó utilizando la media de cada variable.

Tras el proceso, el dataset volvió a presentar cero valores faltantes, quedando apto para las siguientes etapas de modelado.

In [25]:
df_imp["X1"] = df_imp["X1"].fillna(df_imp["X1"].mean())
df_imp["X3"] = df_imp["X3"].fillna(df_imp["X3"].mean())
df_imp["X7"] = df_imp["X7"].fillna(df_imp["X7"].mean())

In [26]:
df_imp.isnull().sum()

X1    0
X2    0
X3    0
X4    0
X5    0
X6    0
X7    0
X8    0
Y1    0
Y2    0
dtype: int64

## 7. Normalización / Estandarización (Transformación)

Las variables predictoras presentan escalas diferentes. Por ejemplo, X1 toma valores entre 0.62 y 0.98, mientras que X2 alcanza valores superiores a 800.

De acuerdo con lo explicado en clase, cuando las variables tienen magnitudes muy distintas, algunas pueden influir más que otras durante el entrenamiento de modelos basados en distancia.

Por esta razón se aplicó una estandarización utilizando StandardScaler, transformando las variables de entrada para que tengan media cercana a 0 y desviación estándar cercana a 1.

Las variables objetivo Y1 (Heating Load) y Y2 (Cooling Load) no fueron transformadas debido a que representan los valores que posteriormente se desean predecir.

In [42]:
from sklearn.preprocessing import StandardScaler

X = df_imp.drop(columns=["Y1", "Y2"])

scaler = StandardScaler()

X_scaled = pd.DataFrame(
    scaler.fit_transform(X),
    columns=X.columns
)

X_scaled.head()

         X1        X2        X3        X4   X5        X6        X7        X8
0  2.044054 -1.785875 -0.562800 -1.470077  1.0 -1.341641 -1.762934 -1.814575
1  2.044054 -1.785875 -0.562800 -1.470077  1.0 -0.447214 -1.762934 -1.814575
2  2.044054 -1.785875 -0.562800 -1.470077  1.0  0.447214 -1.762934 -1.814575
3  2.044054 -1.785875 -0.562800 -1.470077  1.0  1.341641 -1.762934 -1.814575
4  1.286851 -1.229239 -0.000733 -1.198678  1.0 -1.341641 -1.762934 -1.814575

### Resultado de la estandarización

Se observa que las variables transformadas presentan medias cercanas a 0 y desviaciones estándar cercanas a 1.

Esto confirma que la estandarización fue aplicada correctamente y que las diferencias de escala entre las variables originales fueron eliminadas.

El conjunto de datos queda preparado para algoritmos sensibles a la escala, como K-Means, SVM y redes neuronales.

In [43]:
X_scaled.describe()

,X1,X2,X3,X4,X5,X6,X7,X8
count,7.680000e+02,7.680000e+02,7.680000e+02,7.680000e+02,768.000000,768.000000,7.680000e+02,768.000000
mean,4.625929e-18,-4.163336e-16,5.181041e-16,2.174187e-16,0.000000,0.000000,1.480297e-16,0.000000
std,1.000652e+00,1.000652e+00,1.000652e+00,1.000652e+00,1.000652,1.000652,1.000652e+00,1.000652
min,-1.363361e+00,-1.785875e+00,-1.686934e+00,-1.470077e+00,-1.000000,-1.341641,-1.762934e+00,-1.814575
25%,-7.717958e-01,-7.421818e-01,-5.628000e-01,-7.915797e-01,-1.000000,-0.670820,-1.011311e+00,-0.685506
50%,-1.329055e-01,2.319318e-02,-7.328125e-04,1.583159e-01,0.000000,0.000000,1.161243e-01,0.120972
75%,5.296475e-01,7.885681e-01,5.613344e-01,9.725122e-01,1.000000,0.670820,1.243559e+00,0.766154
max,2.044054e+00,1.553943e+00,2.247536e+00,9.725122e-01,1.000000,1.341641,1.243559e+00,1.411336

## 8. Exportar y División del Dataset

El dataset se divide en conjuntos de entrenamiento y prueba utilizando una proporción 80/20.

Esta división permite entrenar modelos posteriormente y evaluar su capacidad de generalización sobre datos no vistos.

In [44]:
df_model = X_scaled.copy()

df_model["Y1"] = df_imp["Y1"]
df_model["Y2"] = df_imp["Y2"]

df_model.head()

,X1,X2,X3,X4,X5,X6,X7,X8,Y1,Y2
0,2.044054,-1.785875,-0.562800,-1.470077,1.0,-1.341641,-1.762934,-1.814575,15.55,21.33
1,2.044054,-1.785875,-0.562800,-1.470077,1.0,-0.447214,-1.762934,-1.814575,15.55,21.33
2,2.044054,-1.785875,-0.562800,-1.470077,1.0,0.447214,-1.762934,-1.814575,15.55,21.33
3,2.044054,-1.785875,-0.562800,-1.470077,1.0,1.341641,-1.762934,-1.814575,15.55,21.33
4,1.286851,-1.229239,-0.000733,-1.198678,1.0,-1.341641,-1.762934,-1.814575,20.84,28.28

In [45]:
X = df_model.drop(columns=["Y1", "Y2"])

y = df_model[["Y1", "Y2"]]

In [48]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)

print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (614, 8)
X_test : (154, 8)
y_train: (614, 2)
y_test : (154, 2)

In [76]:
df_model.to_csv("../data/processed/data_clean.csv",index=False)

print("Dataset exportado correctamente")

Dataset exportado correctamente